# Generated by Django 4.0.3 on 2022-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='passangers',
            field=models.IntegerField(),
        ),
    ]
