# Generated by Django 4.0.3 on 2022-03-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
